services:
  api:
    network_mode: host
    command: ["dotnet", "Arma3Manager.Api.dll", "--config=/app/config/manager.host.toml"]
    ports: []

  frontend:
    environment:
      ARMA3_API_BACKEND: "10.89.0.1:8081"
